project:
  name: "E2E-Power-Demand-MLOps"
  version: "1.0.0"

data_processing:
  raw_data_dir: "./data/raw"
  processed_data_dir: "./data/processed"
  raw_glob_pattern: "power_demand_*.csv"
  combined_raw_filename: "power_demand.csv"
  train_filename: "train.csv"
  stream_filename: "stream.csv"
  split_date: "2023-01-01"

training:
  mlflow:
    tracking_uri: "http://127.0.0.1:5000"
    experiment_name: "E2E Power Demand - Model Train"
    model_name: "lstm_power_demand"
  model_params:
    type: "lstm"
    input_size: 2
    output_size: 1
    hidden_size: 50
    num_layers: 1
    seq_len: 128
  train_params:
    batch_size: 256
    learning_rate: 0.0005
    epochs: 5
  artifacts:
    scaler_path: "scaler"
    model_path: "model"

deployment:
  local_model_dir: "inference_model"
  model_alias: "prod"

inference:
  kafka:
    bootstrap_servers: "localhost:9092"
    topic_name: "power_demand"
  buffer_seed_data_path: "./data/processed/train.csv" # 초기 버퍼를 채울 데이터 경로

dashboard:
  forecast_hours: 60 # 일(days) -> 시간(hours)으로 변경
  refresh_interval_ms: 5000
