mlflow:
  tracking_uri: "http://127.0.0.1:5000"
  experiment_name: "E2E Power demend Platform - Model Train"
  model_name: "lstm_power_demand"

data:
  processed:
    stream: "./data/processed/stream.csv"
    train: "./data/processed/train.csv"
  raw_data_dir: "./data/raw"
  raw_glob_pattern: "power_demand_*.csv"
  combined_raw_path: "./data/raw/power_demand.csv"

model:
  lstm:
    input_size: 2
    output_size: 1
    hidden_size: 50
    num_layers: 1
    seq_len: 128
    
    batch_size: 256
    learning_rate: 0.0005
    epochs: 5

artifacts:
  scaler_path: "scaler"
  model_path: "model"
